version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: increase
    open-pull-requests-limit: 20
    groups:
      dev-deps:
        dependency-type: development
        exclude-patterns: ["remark-*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
